model:
  target: models.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 32
    feature_size: 862
    n_layer_enc: 4
    n_layer_dec: 4
    d_model: 96  # 4 X 24
    timesteps: 200
    sampling_timesteps: 200
    loss_type: 'l2'
    beta_schedule: 'linear'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0

solver:
  base_lr: 1.0e-5
  max_epochs: 18000
  results_folder: ./checkpoints/traffic
  gradient_accumulate_every: 2
  save_cycle: 1800  # max_epochs // 10
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 4000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500
      verbose: False

dataloader:
  train_dataset:
    target: utils.dataset.CustomDataset
    params:
      name: traffic
      proportion: 0.6  # Set to rate < 1 if training conditional generation
      data_root: ./datasets/traffic.csv
      window: 32  # seq_length
      period: train

  test_dataset:
    target: utils.dataset.CustomDataset
    params:
      name: traffic
      proportion: 0.6  # rate
      data_root: ./datasets/traffic.csv
      window: 32  # seq_length
      period: test
      style: separate
      distribution: geometric
    coefficient: 1.0e-2
    step_size: 5.0e-2
    sampling_steps: 50

  batch_size: 128
  sample_size: 512
  shuffle: True